name: flutter_weekend_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.0.1
  modal_progress_hud_nsn: ^0.2.1
  fl_country_code_picker: ^0.0.1
  flutter_progress_hud: ^2.0.2
  flutter_screenutil: ^5.6.0
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
